env:
  CARGO_TERM_COLOR: always

name: Rust
on: [push, pull_request]

jobs:
  test:
    name: cargo test

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: dtolnay/rust-toolchain@stable
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose